//! Raw bindings to `llama.h`, ggml's backend loader and device queries,
//! and the gguf file reader, generated by bindgen at build time
//! (build.rs). Nothing here is written by hand.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unpredictable_function_pointer_comparisons,
    unnecessary_transmutes,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/llama.rs"));
